export const ENTER_LOBBY = 'chat.enterLobby'
export const LEAVE_LOBBY = 'chat.leaveLobby'
export const ENTER_ROOM = 'chat.enterRoom'
export const LEAVE_ROOM = 'chat.leaveRoom'
export const DISPATCH_MESSAGE = 'chat.dispatchMessage'
export const SEND_INVITATION = 'chat.sendInvitation'
