export const UPDATE_ROOM_LIST = 'chat.fetchRoomList'
export const UPDATE_ROOM_INFO = 'chat.fetchRoomInfo'
export const FETCH_ALL_PEOPLE = 'chat.fetchAllPeople'
export const DISPATCH_MESSAGE = 'chat.dispatchMessage'
export const JOIN_ROOM = 'chat.joinRoom'
export const LEAVE_ROOM = 'chat.leaveRoom'
export const SEND_INVITATION = 'chat.invite'
