export const SET_ROOMS = 'chat.setRooms'
export const SET_PEOPLE = 'chat.setPeople'
export const SET_ROOM = 'chat.setRoom'
export const CLEAR = 'chat.clear'
export const ADD_MESSAGE = 'chat.addMessage'
export const ADD_USER = 'chat.addUser'
export const REMOVE_USER = 'chat.removeUser'
export const IMAGE_UPLOADED = 'chat.imageUploaded'
