module.exports = {
  REQ_REGISTER_ID: 'REQ_REGISTER_ID',
  REQ_ROOM_LIST: 'REQ_ROOM_LIST',
  REQ_ROOM_INFO: 'REQ_ROOM_INFO',
  REQ_PEOPLE_IN_ROOM: 'REQ_PEOPLE_IN_ROOM',
  REQ_MESSAGE: 'REQ_MESSAGE',
  REQ_INVITE: 'REQ_INVITE',
  REQ_JOIN: 'REQ_JOIN',
  REQ_LEAVE: 'REQ_LEAVE',
  RES_NEW_MESSAGE: 'RES_NEW_MESSAGE',
  RES_JOINED: 'RES_JOINED',
  RES_LEFT: 'RES_LEFT',
  RES_INVITED: 'RES_INVITED',
}
